[package]
name = "officedays"
version = "0.2.3"
edition = "2021"

[dependencies]
dirs = "5.0.1"
toml = "0.8.19"
serde = { version = "1.0.217", features = ["derive"] }
chrono = { version = "0.4.39", features = ["serde"] }
